Create documentation.

diff --git a/etc/Allmake b/etc/Allmake
--- a/etc/Allmake
+++ b/etc/Allmake
@@ -48,33 +48,42 @@ do
    esac
 done
 
+if [ $0 != "./etc/Allmake" ]; then 
+    echo "Error: Must run this script from mops-c-Git/"
+    exit 1
+fi
+
 odesolvers=(cvode cvodes radau kinsol ida)
 io=(camxml comostrings)
 folders=(sprogc geometry camflow sweepc mopsc brush)
 
 if [ $cleanall -eq 1 ]; then
+    echo "Cleaning all libraries."
     for element in ${odesolvers[@]}
     do
-        make --directory=src/odesolvers/$element -s --file="new"$element"Makefile" cleanlibs
+        make --directory=src/odesolvers/$element -s --file="Makefile" cleanlibs
+        echo "$element cleaned."
     done
     for element in ${io[@]}
     do
-        make --directory=src/io/$element -s --file="new"$element"Makefile" cleanlibs
+        make --directory=src/io/$element -s --file="Makefile" cleanlibs
+        echo "$element cleaned."
     done
     for element in ${folders[@]}
     do
-        make --directory=src/$element -s --file="new"$element"Makefile" cleanlibs
+        make --directory=src/$element -s --file="Makefile" cleanlibs
+        echo "$element cleaned."
     done
+    echo "Libraries cleaned successfully."
     exit
 fi
 
 echo "Make everything with debug set to $debug."
 
 echo "Make ODE solver libraries:"
-odesolvers=(cvode cvodes radau kinsol ida)
 for element in ${odesolvers[@]}
 do
-    make --directory=src/odesolvers/$element -s --file="new"$element"Makefile" clean all debug=$debug
+    make --directory=src/odesolvers/$element -s --file="Makefile" clean all debug=$debug
     if [ $? -gt 0 ] ; then
         echo make $element failed
         exit
@@ -84,10 +93,9 @@ do
 done
 
 echo "Make IO libraries:"
-io=(camxml comostrings)
 for element in ${io[@]}
 do
-    make --directory=src/io/$element -s --file="new"$element"Makefile" clean all debug=$debug
+    make --directory=src/io/$element -s --file="Makefile" clean all debug=$debug
     if [ $? -gt 0 ] ; then
         echo make $element failed
         exit
@@ -97,10 +105,9 @@ do
 done
 
 echo "Make the rest:"
-folders=(sprogc geometry camflow sweepc mopsc brush)
 for element in ${folders[@]}
 do
-    make --directory=src/$element -s --file="new"$element"Makefile" clean all debug=$debug
+    make --directory=src/$element -s --file="Makefile" clean all debug=$debug
     if [ $? -gt 0 ] ; then
         echo make $element failed
         exit
@@ -108,3 +115,5 @@ do
         echo make $element success
     fi
 done
+
+echo "Allmake successful."
